### ISSUE TITLE
Option to change genetic code (translation table)?

### ISSUE THREAD

**Issue by sminot** [soedinglab/plass#2]
## Expected Behavior
Plass provides a flag for the translation table (genetic code) used to perform the conceptual six-frame translation of nucleotides to amino acids. For sequences expected to be bacterial this would correspond to the translation table 11. 

## Current Behavior
There is no option for the translation table in the command line flags.

## Your Environment
I am running Plass from the static binary hosted at https://mmseqs.com/plass/plass-static_sse41.tar.gz

**Comment by milot-mirdita** [comment]
I just exposed the parameters in the last commit (d4071700cba48fd6551173329f3b71629cbf829e).

You need two parameters: `--use-all-table-starts --translation-table N`.

These tables are implemented:
```
1) CANONICAL, 2) VERT_MITOCHONDRIAL, 3) YEAST_MITOCHONDRIAL, 4) MOLD_MITOCHONDRIAL, 5) INVERT_MITOCHONDRIAL, 6) CILIATE, 9) FLATWORM_MITOCHONDRIAL, 10) EUPLOTID, 11) PROKARYOTE, 12) ALT_YEAST, 13) ASCIDIAN_MITOCHONDRIAL, 14) ALT_FLATWORM_MITOCHONDRIAL, 15) BLEPHARISMA, 16) CHLOROPHYCEAN_MITOCHONDRIAL, 21) TREMATODE_MITOCHONDRIAL, 22) SCENEDESMUS_MITOCHONDRIAL, 23) THRAUSTOCHYTRIUM_MITOCHONDRIAL, 24) PTEROBRANCHIA_MITOCHONDRIAL, 25) GRACILIBACTERIA, 26) PACHYSOLEN, 27) KARYORELICT, 28) CONDYLOSTOMA, 29) MESODINIUM, 30) PERTRICH, 31) BLASTOCRITHIDIA
```

**Comment by sminot** [comment]
Do you have any static binaries available from that commit? I'd love to test it out but I don't have the easiest time building from source.

**Comment by milot-mirdita** [comment]
Download the static binary again, it always points to the latest commit (that codeship or travis build).

What can we do to make the compiling process easier?

**Comment by sminot** [comment]
Any chance you could link to the Dockerfile you use to build soedinglab/plass?

**Comment by sminot** [comment]
An alternative to supporting the build from source would just be to tag the different versions so that you can pull a docker image the corresponds to a particular GitHub commit. That would help users ensure reproducible execution, while also letting them just use your Docker images for execution.

**Comment by milot-mirdita** [comment]
Its in the root folder of the repository:
https://github.com/soedinglab/plass/blob/master/Dockerfile

I forgot to add the docker tag for releases. I am trying to get docker cloud to tag them now automatically.

**Comment by sminot** [comment]
Well, now I feel a bit silly :-) Thanks!

**Comment by sminot** [comment]
Ok, I can confirm now that the translation table param works in my hands. Thanks!
