### ISSUE TITLE
Issue with Docker image soedinglab/plass:latest

### ISSUE THREAD

**Issue by winkel111** [soedinglab/plass#34]
When I try to run plass in a docker container from image soedinglab/plass:latest on my Linux box with the command: 

user@ubuntu:~/data$ docker run -t -i --rm -v "$(pwd):/app" -w /app soedinglab/plass:latest assemble reads1 reads2 assembly.fas tmp

I get this error message:
/usr/local/bin/plass: 8: /usr/local/bin/plass: Syntax error: newline unexpected (expecting ")")

The container runs fine with soedinglab/plass:version-3 or earlier.

Environment:
Ubuntu 20.04.2 LTS focal x86_64 
Kernel: 5.4.0-65-generic
Docker engine: 20.10.3 linux/amd64

**Comment by milot-mirdita** [comment]
Whoops, thanks for the bug report.
You can also use the biocontainer based on the conda plass (see https://biocontainers.pro/tools/plass). 
The docker hub docker should be rebuilt soon.

**Comment by winkel111** [comment]
It works! Thanks for the quick fix!
