### ISSUE TITLE
Alternative codon table 

### ISSUE THREAD

**Issue by aabaricalla** [soedinglab/plass#45]
I recently found this tool and I'll try as soon as possible.
I'm trying to reconstruct a mitochondrial genome without closely related specie, so I think this approach could be a better way to do it, but I'm concern about the codon table.
There is any chance to use the codon 5 table (invertebrate)?

**Comment by milot-mirdita** [comment]
You should be able to use  `--use-all-table-starts 1 --translation-table 5` , however, we have not extensively tested alternative codon tables.

**Comment by aabaricalla** [comment]
Thanks a lot!! I'll be sending you my test results ASAP.
