### ISSUE TITLE
Output FASTA header format?

### ISSUE THREAD

**Issue by sjaenick** [soedinglab/plass#6]
Assembled protein sequences contain additional information, e.g.

[Orf: 39, 242, 18446744073709551615, 1, 1]

What is the meaning of these numbers? Is there any coverage information 
included? (If not, can it be added?)

Thanks.

**Comment by martin-steinegger** [comment]
@sjaenick thank you for trying Plass. 👍  

The information is current just the open reading frame of the center fragment that got extended. So it is not very useful. You can compute the coverage by mapping  back the reads using the [mmseqs2](https://github.com/soedinglab/mmseqs2) map workflow.

**Comment by sjaenick** [comment]
Thanks.
