### ISSUE TITLE
Automated Docker images with sha256 tags

### ISSUE THREAD

**Issue by sminot** [soedinglab/plass#7]
## Expected Behavior
The ideal source for reproducible Docker images is a docker server that allows you to request images by sha256 hash. Quay provides that service with automated integration with GitHub.

## Current Behavior
The only issue with the Docker image currently hosted on dockerhub is that users cannot pull based on sha256 hash, and so you cannot achieve the guaranteed reproducibility by knowing that two versions pulled down are 100% identical.

## Solution
It is rather easy to set up a repository on Quay that automatically builds from a Dockerfile within a GitHub repo on each commit (or release). If you were to set that up once, then users could pull down a single canonical Docker image for each release of Plass. See [the docs](https://docs.quay.io/guides/building.html) for more details.

**Comment by milot-mirdita** [comment]
I am not sure I understand what you mean with hash. You want to be able pull the docker image based on the git commit hash? We can also add that tag to Docker Hub. I am not sure I understand what Quay does better. I am a bit apprehensive about adding even more external services, since we already depend on quite a few (Travis, Codeship, Docker Hub, Appveyor for MMseqs2).

**Comment by sminot** [comment]
Tagging the docker image on the git commit hash should be perfect, actually. Thanks very much!


---------------------------------------

Samuel Minot, PhD
Microbiome Research Initiative
Fred Hutchinson Cancer Research Center
sminot@fredhutch.org<mailto:sminot@fredhutch.org>
206-667-2884
https://minot.bio

On Feb 11, 2019, at 2:03 AM, Milot Mirdita <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure I understand what you mean with hash. You want to be able pull the docker image based on the git commit hash? We can also add that tag to Docker Hub. I am not sure I understand what Quay does better. I am a bit apprehensive about adding even more external services, since we already depend on quite a few (Travis, Codeship, Docker Hub, Appveyor for MMseqs2).

**Comment by milot-mirdita** [comment]
So I just checked, Docker Hub does not allow you to use the Git Hash for build tagging. I don't really want to migrate to another service. Our version string (and thus docker-tag) format is {incrementing number}.{first few characters of git hash}. Is that enough for your requirements?

**Comment by sminot** [comment]
I think that's more than enough, thanks!
