### ISSUE TITLE
Combining single and paired reads

### ISSUE THREAD

**Issue by mooreryan** [soedinglab/plass#8]
Just wondering, is there any way to combine single and paired reads from the same library into a single assembly?

**Comment by martin-steinegger** [comment]
There is no internal solution to use paired end reads and single end at the same time. But you could used FLASH (https://ccb.jhu.edu/software/FLASH/) to merge the reads and concat them with the single end reads and just use a single parameter. 

         plass assemble reads.fastq assembly.fasta tmp

**Comment by mooreryan** [comment]
Perfect, that's exactly what I tried to do!
